from fastapi import FastAPI

app = FastAPI()


@app.post("/generate-conclusion")
async def generate_conclusion():
    conclusion = "This is the conclusion generated by the backend."
    return {"conclusion": conclusion}
